# Generated by Django 6.0.5 on 2026-06-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='valeurs_normales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
